# VIPAccess Configuration

# Is plugin enabled
enabled: true

# Language (en, ru)
language: ru

# Permission required to join full server
required-permission: "server.vip"

# Anti-Bot Protection Settings
anti-bot:
  enabled: true
  threshold: 50
  protection-duration: 60
  punishment: KICK