name: VIPAccess-Rework
version: '1.1-SNAPSHOT'
main: com.sunrisestudio.vipaccess.VIPAccess
api-version: '1.21'
authors: [ Cooking, t1pe ]
softdepend: [PlaceholderAPI]
commands:
  vipaccess:
    description: Main command
    usage: /vipaccess
    aliases: [vipa]
    permission: vipaccess.admin
permissions:
  vipaccess.admin:
    description: Full access
    default: op
  vipaccess.bypass:
    description: Bypass checks
    default: op